name: CI

on:
  push:
    branches: [main]

permissions: write-all

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Установка SFML (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install -y libsfml-dev

      - name: Установка SFML (macOS)
        if: matrix.os == 'macos-latest'
        run: brew install sfml@2

      - name: Конфигурация CMake (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: cmake -S . -B build

      - name: Конфигурация CMake (macOS)
        if: matrix.os == 'macos-latest'
        run: cmake -S . -B build -DSFML_DIR=$(brew --prefix sfml@2)/lib/cmake/SFML

      - name: Сборка
        run: cmake --build build
